source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'libPusher', '~> 1.5'
pod 'UICKeyChainStore'
pod 'FLAnimatedImage', '~> 1.0'
pod 'Typhoon'
pod 'Mixpanel'
pod 'ObjectiveRecord', '1.5.0'
pod 'MarqueeLabel'
